---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/internet-provider
  label: Internet Providers
  create: all
  match: "**/*"
- type: directory
  path: content/js-library
  label: JS Libraries
  create: all
  match: "**/*"
- type: directory
  path: content/cms
  label: CMS
  create: all
  match: "**/*"
- type: directory
  path: content/digital-agency
  label: Digital Agencies
  create: all
  match: "**/*"
- type: directory
  path: content/css-framework
  label: CSS Frameworks
  create: all
  match: "**/*"
- type: directory
  path: content/web-host
  label: Web Hosts
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.49'
